# Generated by Django 4.0 on 2021-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('deparment', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('visiting_person', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('al_time', models.TimeField()),
                ('in_office', models.BooleanField(default=False, verbose_name='Is in the Office')),
            ],
        ),
    ]
